apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hr-finance-data-pvc
  namespace: hr-finance-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hr-finance-models-pvc
  namespace: hr-finance-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 50Gi
